name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        # 安装编译工具
        sudo apt-get install build-essential cmake ninja-build
        # 其他库
        sudo apt-get install -y libreadline-dev libsqlite3-dev curl libcunit1-dev
        
    - name: Configure build
      run: |
        mkdir build
        cmake -B build -G Ninja
        
    - name: Build project
      run: |
        cmake --build build
